# This docker-compose file brings up an example instance of WebformulierenVerwerker.
# 
# A H2 file-based database is used as example. This is not recommended for production environments.
#
# To use this docker-compose file:
#    docker compose <command> (eg. up, down)
#
# Access the Frank!Console by navigating to http://localhost:8080/.
#
services:
  frank:
    image: wearefrank/webformulierenverwerker:${VERSION:-10.1.0}
    environment:
      TZ: ${TIME_ZONE:-Europe/Amsterdam}
      dtap.stage: ${DTAP_STAGE:-LOC}
      credentialFactory.class: org.frankframework.credentialprovider.PropertyFileCredentialFactory
      credentialFactory.map.properties: /opt/frank/secrets/credentials.properties
    env_file:
      - .env
    volumes:
      - h2-data:/opt/frank/h2:rw
      - logs:/usr/local/tomcat/logs:rw
      - ${SECRETS_PATH:-./src/main/secrets}:/opt/frank/secrets
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped

volumes:
  logs:
  h2-data:
