version: '3.8'

services:
  frank:
    build: .
    image: wearefrank/webformulierenverwerker:${VERSION:-latest}
    ports:
      - "${PORT:-8080}:8080"
    environment:
      application.server.type.custom: ${TRANSACTION_MANAGER:-NARAYANA}
      credentialFactory.class: nl.nn.credentialprovider.PropertyFileCredentialFactory
      credentialFactory.map.properties: /opt/frank/secrets/credentials.properties
      TZ: ${TIME_ZONE:-Europe/Amsterdam}
    env_file:
      - .env
    volumes:
      - ${SECRETS_PATH:-./secrets}:/opt/frank/secrets
      - ./src/main/resources/oauth-role-mapping.properties:/opt/frank/resources/oauth-role-mapping.properties
    restart: unless-stopped

