# Local URL so testing can be done with the SoapUI Mockservice.
corsa.url=http://host.docker.internal:8081/
# Use if running via Frank-Runner:
# corsa.url=http://localhost:8081/

# URLs to CAReL (currently SoapUI mock urls)
# carel_zds_ontvangasynchroon.url=http://localhost:7771/mock/services/proxy/generic/zds/OntvangAsynchroon
# carel_zds_vrijbericht.url=http://localhost:7772/mock/services/proxy/generic/zds/VrijBericht
carel_zds_ontvangasynchroon.url=http://host.docker.internal:7771/mock/services/proxy/generic/zds/OntvangAsynchroon
carel_zds_vrijbericht.url=http://host.docker.internal:7772/mock/services/proxy/generic/zds/VrijBericht

# URL to OpenZaakBrug (currently SoapUI mock url)
# openzaakbrug_zds_vrijbericht.url=http://localhost:7772/mock/services/proxy/generic/zds/VrijBericht
openzaakbrug_zds_vrijbericht.url=http://host.docker.internal:7772/mock/services/proxy/generic/zds/VrijBericht

stub4testtool.configuration=false
