# URL to Corsa (WSDL can be retrieved at http://swfkvt01/wsCorsa7/Corsa72WS4j.asmx?wsdl)
corsa.url=http://swfkvt01/wsCorsa7/Corsa72WS4j.asmx

# URLs to CAReL (currently SoapUI mock urls)
carel_zds_ontvangasynchroon.url=http://localhost:7771/mock/services/proxy/generic/zds/OntvangAsynchroon
carel_zds_vrijbericht.url=http://localhost:7772/mock/services/proxy/generic/zds/VrijBericht

# URL for compliance with the Kodision Firewall.
wsdl.location=https://testtsjinstbus.sudwestfryslan.nl/webformulierenverwerker/services/WebformulierenVerwerker

ConnectionID=Corsa

WebformulierenVerwerker.CreateDocument-Stylesheet = xsl/OpslaanInkNatuurlijkPersoon/Message2CreateDocument.xsl
WebformulierenVerwerker.CreateDocumentCompany-Stylesheet = xsl/OpslaanInkNietNatuurlijkPersoon/Message2CreateDocumentCompany.xsl
