# Place to keep local credentials if needed.
# The deployments should use the credentials.properties placed in the secrets folder

jdbc/username=frank
jdbc/password=frank

# ZAC - Documenten API (Open Zaak, poort 8001): JWT client secret
zac.api.secret=webformulierenverwerkerSecret

# ZAC - Objecten API (poort 8010): Django REST Framework token
zac.objecten.token=cd63e158f3aca276ef284e3033d020a22899c728
