name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  analyze-commits:
    runs-on: ubuntu-latest
    outputs:
      version-next: ${{ steps.next-version.outputs.release-version }}
      version-next-tag: ${{ steps.next-version.outputs.release-tag }}
      version-next-type: ${{ steps.next-version.outputs.release-type }}
    steps:
      - uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
      
      - name: "Setup Node"
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af #4.1.0
        with:
          node-version: 20
      
      - name: Install dependencies
        run: yarn global add semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec @semantic-release/release-notes-generator @semantic-release/commit-analyzer conventional-changelog-conventionalcommits
      
      - name: Get next version
        id: next-version
        run: semantic-release --dryRun
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ci:
    uses: wearefrank/ci-cd-templates/.github/workflows/ci-generic.yml@bdd980ea3327366c72f021c09685abc676b74585 #1.0.12
    needs: analyze-commits
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    if: ${{ needs.analyze-commits.outputs.version-next-type != '' }}
    with:
      version: ${{ needs.analyze-commits.outputs.version-next }}

  release:
    runs-on: ubuntu-latest
    needs: 
      - analyze-commits
      - ci
    steps:
      - uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Pre-build Artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #4.1.8
        with:
          pattern: pre-build-*
          merge-multiple: true
  
      - name: Download Build Artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #4.1.8
        with:
          pattern: build-*
          merge-multiple: true

      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af #4.1.0
        with:
          node-version: 20
      
      - name: Install dependencies
        run: yarn global add semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec @semantic-release/release-notes-generator @semantic-release/commit-analyzer conventional-changelog-conventionalcommits
      
      - name: Semantic Release
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-release:
    uses: wearefrank/ci-cd-templates/.github/workflows/docker-release-generic.yml@bdd980ea3327366c72f021c09685abc676b74585 #1.0.12
    needs: 
      - analyze-commits
      - release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      dockerhub-username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKER_PASSWORD }}
    with:
      version: ${{ needs.analyze-commits.outputs.version-next }}

  docusaurus-release:
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: 
      - release
    # Set to true to enable Docusaurus publishing to GitHub Pages
    if: false
    uses: wearefrank/ci-cd-templates/.github/workflows/docusaurus-release.yml@bdd980ea3327366c72f021c09685abc676b74585 #1.0.12
